artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  final_data: artifacts/data_transformation/final_data.csv

data_spliting:
  root_dir: artifacts/data_spliting
  data_path: artifacts/data_transformation/final_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_spliting/train.csv
  test_data_path: artifacts/data_spliting/test.csv
  scaler: scaler.joblib
  Potato: artifacts/model_trainer/Potato

model_evaluation:
  root_dir: artifacts/model_evaluation
  train_data_path: artifacts/data_spliting/train.csv
  test_data_path: artifacts/data_spliting/test.csv
  Potato: artifacts/model_trainer/artifacts/model_trainer/Potato
  scaler: artifacts/model_triner/scaler.joblib
  
